version: "3.7"

services:
  proxy:
    image: ghcr.io/iandday/plant_tracker_proxy:latest
    restart: always
    volumes:
      - ./media:/media
      - ./static:/static
    ports:
      - 80:80
    depends_on:
      - django
  django:
    image: ghcr.io/iandday/plant_tracker:latest
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./media:/media
      - ./static:/static
    environment:
      - SECRET_KEY=${SECRET_KEY}
      - JWT_SIGNING_KEY=${JWT_SIGNING_KEY}
      - JWT_ACCESS_TOKEN_LIFETIME_MINUTES=${JWT_ACCESS_TOKEN_LIFETIME_MINUTES}
      - JWT_ACCESS_REFRESH_LIFETIME_DAYS=${JWT_ACCESS_REFRESH_LIFETIME_DAYS}
      - DEBUG=${DEBUG}
      - ENABLE_REGISTRATION=${ENABLE_REGISTRATION}
      - MEDIA_PATH=${MEDIA_PATH}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
      - ADMIN_EMAIL=${ADMIN_EMAIL}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - DATABASE_URL=psql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
    depends_on:
      - db
  db:
    image: postgres:14.5
    volumes:
      - ./db:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -q -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
