version: "3.7"

services:
  django:
    depends_on:
      - db
    ports:
      - "8000:8000"
    build:
      dockerfile: Dockerfile
      context: ./
    volumes:
      - ./plant_tracker:/home/apiuser/plant_tracker
      - ./media:/media
    env_file: .env
    #environment:
    # - DATABASE_URL=postgresql+psycopg2://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
    # - TREFLE_KEY=${TREFLE_KEY}
    # - JWT_REFRESH_SECRET_KEY=${JWT_REFRESH_SECRET_KEY}
    # - JWT_SECRET_KEY=${JWT_SECRET_KEY}
    # - ENABLE_REGISTRATION=${ENABLE_REGISTRATION}
    # - FRONTEND_URL=${FRONTEND_URL}
  db:
    image: postgres:14.5
    ports:
      - "5432:5432"
    volumes:
      - ./db:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -q -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=pgadmin@pgadmin.org
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_PASSWORD}
    ports:
      - "5050:80"
    depends_on:
      - db
