/* tslint:disable */
/* eslint-disable */
/**
 * Book Store API
 * Book Store API for renting books and notifying available/returned books in a store
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface PlantPost
 */
export interface PlantPost {
    /**
     * 
     * @type {string}
     * @memberof PlantPost
     */
    'area_id'?: string;
    /**
     * 
     * @type {string}
     * @memberof PlantPost
     */
    'purchase_date'?: string;
    /**
     * 
     * @type {boolean}
     * @memberof PlantPost
     */
    'graveyard'?: boolean;
    /**
     * 
     * @type {string}
     * @memberof PlantPost
     */
    'death_date'?: string;
    /**
     * 
     * @type {string}
     * @memberof PlantPost
     */
    'name'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PlantPost
     */
    'common_name'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PlantPost
     */
    'scientific_name'?: string | null;
}

