"""migration

Revision ID: 27aaac9663da
Revises: c4a0be368ee8
Create Date: 2023-09-24 20:11:54.042975

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '27aaac9663da'
down_revision: Union[str, None] = 'c4a0be368ee8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('other_name',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_other_name_id'), 'other_name', ['id'], unique=False)
    op.create_table('plant_other_name',
    sa.Column('plant_id', sa.UUID(), nullable=False),
    sa.Column('other_name_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['other_name_id'], ['other_name.id'], ),
    sa.ForeignKeyConstraint(['plant_id'], ['plant.id'], ),
    sa.PrimaryKeyConstraint('plant_id', 'other_name_id')
    )
    op.drop_column('plant', 'aka')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('plant', sa.Column('aka', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_table('plant_other_name')
    op.drop_index(op.f('ix_other_name_id'), table_name='other_name')
    op.drop_table('other_name')
    # ### end Alembic commands ###
