"""migration

Revision ID: 6fdd31b55f7f
Revises: 77e604ebd399
Create Date: 2023-09-23 20:17:10.714908

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6fdd31b55f7f'
down_revision: Union[str, None] = '77e604ebd399'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('plant', sa.Column('sunlight_desc', sa.String(), nullable=True))
    op.add_column('plant', sa.Column('watering_desc', sa.String(), nullable=True))
    op.drop_column('plant', 'sunlight_long')
    op.drop_column('plant', 'watering_long')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('plant', sa.Column('watering_long', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('plant', sa.Column('sunlight_long', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('plant', 'watering_desc')
    op.drop_column('plant', 'sunlight_desc')
    # ### end Alembic commands ###
