"""migration

Revision ID: 49a958450b01
Revises: 6fdd31b55f7f
Create Date: 2023-09-23 20:27:39.284898

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '49a958450b01'
down_revision: Union[str, None] = '6fdd31b55f7f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pruning_month', sa.Column('month', sa.String(), nullable=True))
    op.drop_column('pruning_month', 'method')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pruning_month', sa.Column('method', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('pruning_month', 'month')
    # ### end Alembic commands ###
