"""migration

Revision ID: ae1d512e88d0
Revises: 4a4f8a103024
Create Date: 2023-09-17 21:48:57.120608

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ae1d512e88d0'
down_revision: Union[str, None] = '4a4f8a103024'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('propagation',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('method', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_propagation_id'), 'propagation', ['id'], unique=False)
    op.create_table('plant_propagation',
    sa.Column('plant_id', sa.UUID(), nullable=False),
    sa.Column('propagation_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['plant_id'], ['plant.id'], ),
    sa.ForeignKeyConstraint(['propagation_id'], ['propagation.id'], ),
    sa.PrimaryKeyConstraint('plant_id', 'propagation_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('plant_propagation')
    op.drop_index(op.f('ix_propagation_id'), table_name='propagation')
    op.drop_table('propagation')
    # ### end Alembic commands ###
