"""migration

Revision ID: 1a71bed779ab
Revises: ae1d512e88d0
Create Date: 2023-09-20 21:24:29.285595

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1a71bed779ab'
down_revision: Union[str, None] = 'ae1d512e88d0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pruning_month',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('method', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pruning_month_id'), 'pruning_month', ['id'], unique=False)
    op.create_table('sunlight',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('method', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sunlight_id'), 'sunlight', ['id'], unique=False)
    op.create_table('plant_pruning_month',
    sa.Column('plant_id', sa.UUID(), nullable=False),
    sa.Column('pruning_month_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['plant_id'], ['plant.id'], ),
    sa.ForeignKeyConstraint(['pruning_month_id'], ['pruning_month.id'], ),
    sa.PrimaryKeyConstraint('plant_id', 'pruning_month_id')
    )
    op.create_table('plant_sunlight',
    sa.Column('plant_id', sa.UUID(), nullable=False),
    sa.Column('sunlight_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['plant_id'], ['plant.id'], ),
    sa.ForeignKeyConstraint(['sunlight_id'], ['sunlight.id'], ),
    sa.PrimaryKeyConstraint('plant_id', 'sunlight_id')
    )
    op.add_column('plant', sa.Column('sunlight_long', sa.String(), nullable=True))
    op.add_column('plant', sa.Column('watering_long', sa.String(), nullable=True))
    op.drop_column('plant', 'watering')
    op.drop_column('plant', 'sunlight')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('plant', sa.Column('sunlight', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('plant', sa.Column('watering', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('plant', 'watering_long')
    op.drop_column('plant', 'sunlight_long')
    op.drop_table('plant_sunlight')
    op.drop_table('plant_pruning_month')
    op.drop_index(op.f('ix_sunlight_id'), table_name='sunlight')
    op.drop_table('sunlight')
    op.drop_index(op.f('ix_pruning_month_id'), table_name='pruning_month')
    op.drop_table('pruning_month')
    # ### end Alembic commands ###
