"""migration

Revision ID: c1a156669fcb
Revises: a8c990837d11
Create Date: 2023-09-14 01:30:06.040117

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c1a156669fcb'
down_revision: Union[str, None] = 'a8c990837d11'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('plant', sa.Column('photo_url', sa.String(), nullable=False))
    op.drop_constraint('plant_photo_key', 'plant', type_='unique')
    op.create_unique_constraint(None, 'plant', ['photo_url'])
    op.drop_column('plant', 'photo')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('plant', sa.Column('photo', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'plant', type_='unique')
    op.create_unique_constraint('plant_photo_key', 'plant', ['photo'])
    op.drop_column('plant', 'photo_url')
    # ### end Alembic commands ###
