"""migration

Revision ID: 3a32ab3b9f0f
Revises: 
Create Date: 2023-09-13 22:14:06.085398

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3a32ab3b9f0f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plant',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('aka', sa.String(), nullable=True),
    sa.Column('cycle', sa.String(), nullable=True),
    sa.Column('plant_type', sa.String(), nullable=True),
    sa.Column('pruning_amount', sa.Integer(), nullable=True),
    sa.Column('pruning_interval', sa.String(), nullable=True),
    sa.Column('watering_period', sa.String(), nullable=True),
    sa.Column('watering_benchmark', sa.String(), nullable=True),
    sa.Column('purchase_date', sa.Date(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('photo', sa.String(), nullable=False),
    sa.Column('sunlight', sa.String(), nullable=True),
    sa.Column('watering', sa.String(), nullable=True),
    sa.Column('location', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('photo')
    )
    op.create_index(op.f('ix_plant_id'), 'plant', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_plant_id'), table_name='plant')
    op.drop_table('plant')
    # ### end Alembic commands ###
