"""migration

Revision ID: 96e6e39173b5
Revises: c1a156669fcb
Create Date: 2023-09-14 01:54:08.956089

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '96e6e39173b5'
down_revision: Union[str, None] = 'c1a156669fcb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('plant', 'photo_url',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('plant', 'photo_url',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
