"""migration

Revision ID: 1557129f7b13
Revises: 49a958450b01
Create Date: 2023-09-24 19:27:09.534494

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1557129f7b13'
down_revision: Union[str, None] = '49a958450b01'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('plant', 'watering_desc')
    op.drop_column('plant', 'sunlight_desc')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('plant', sa.Column('sunlight_desc', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('plant', sa.Column('watering_desc', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
