"""migration

Revision ID: a8c990837d11
Revises: 3a32ab3b9f0f
Create Date: 2023-09-14 01:27:34.870227

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a8c990837d11'
down_revision: Union[str, None] = '3a32ab3b9f0f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('common_name',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_common_name_id'), 'common_name', ['id'], unique=False)
    op.create_table('plant_common_name',
    sa.Column('plant_id', sa.UUID(), nullable=False),
    sa.Column('common_name_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['common_name_id'], ['common_name.id'], ),
    sa.ForeignKeyConstraint(['plant_id'], ['plant.id'], ),
    sa.PrimaryKeyConstraint('plant_id', 'common_name_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('plant_common_name')
    op.drop_index(op.f('ix_common_name_id'), table_name='common_name')
    op.drop_table('common_name')
    # ### end Alembic commands ###
