# Generated by Django 5.0.3 on 2024-04-05 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0004_alter_plant_common_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant',
            name='scientific_name',
            field=models.TextField(blank=True, null=True),
        ),
    ]
