# Generated by Django 5.0.3 on 2024-04-05 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0005_alter_plant_scientific_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant',
            name='purchase_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
