# Generated by Django 5.0.3 on 2024-04-11 11:21

from django.db import migrations

activities = [
    {
        "name": "Water",
        "description": "Application of water to the soil for photosynthesis, for cooling, and to transport minerals and nutrients from the soil and into the plant",
    },
    {
        "name": "Fertilizer Application",
        "description": "Increasing nutrient availability through the application of chemicals",
    },
    {
        "name": "Biostimulant Application",
        "description": "a substance or micro-organism that, when applied to seeds, plants, or the rhizo-sphere, stimulates natural processes to enhance or benefit nutrient uptake, nutrient efficiency, and tolerance to abiotic stress",
    },
    {"name": "Prune", "description": "Selecting trimming of branches"},
    {
        "name": "Re-pot",
        "description": "Transfering to a bigger pot to allow room for growth",
    },
    {
        "name": "Quarantine Start",
        "description": "Starting period of isolation after purchasing or identification of infestation",
    },
    {
        "name": "Quarantine End",
        "description": "Ending period of isolation after purchasing or identification of infestation",
    },
    {
        "name": "Insecticide Treatment",
        "description": "Application of product to remove of prevent infestation",
    },
    {
        "name": "Observation",
        "description": "Documenation of the plant's current state",
    },
    {
        "name": "Cleaning",
        "description": "Removing dust and other matter from leaves to allow absorption of light and photosynthesis",
    },
    {
        "name": "Misting",
        "description": "Application of water to leaves to increased humidty and prevent leaves from drying out",
    },
]


def load_activites(apps, schema_editor):
    Activity = apps.get_model("tracker", "Activity")
    for act in activities:
        Activity.objects.create(**act)


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0008_remove_activity_user"),
    ]

    operations = [migrations.RunPython(load_activites)]
