/* tslint:disable */
/* eslint-disable */
/**
 * Book Store API
 * Book Store API for renting books and notifying available/returned books in a store
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { LocationOut } from './location-out';
// May contain unused imports in some cases
// @ts-ignore
import { UserSchema } from './user-schema';

/**
 * 
 * @export
 * @interface AreaOut
 */
export interface AreaOut {
    /**
     * 
     * @type {string}
     * @memberof AreaOut
     */
    'name': string;
    /**
     * 
     * @type {string}
     * @memberof AreaOut
     */
    'id': string;
    /**
     * 
     * @type {LocationOut}
     * @memberof AreaOut
     */
    'location': LocationOut;
    /**
     * 
     * @type {UserSchema}
     * @memberof AreaOut
     */
    'user': UserSchema;
}

