/* tslint:disable */
/* eslint-disable */
/**
 * Book Store API
 * Book Store API for renting books and notifying available/returned books in a store
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { PlantOut } from './plant-out';

/**
 * 
 * @export
 * @interface BulkPlantCreateResponse
 */
export interface BulkPlantCreateResponse {
    /**
     * 
     * @type {Array<PlantOut>}
     * @memberof BulkPlantCreateResponse
     */
    'created'?: Array<PlantOut>;
    /**
     * 
     * @type {{ [key: string]: string; }}
     * @memberof BulkPlantCreateResponse
     */
    'errors'?: { [key: string]: string; };
}

