/* tslint:disable */
/* eslint-disable */
/**
 * Plant Tracker API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { Activity } from './activity';

/**
 * 
 * @export
 * @interface Entry
 */
export interface Entry {
    /**
     * 
     * @type {string}
     * @memberof Entry
     */
    'id': string;
    /**
     * 
     * @type {Array<Activity>}
     * @memberof Entry
     */
    'activities': Array<Activity>;
    /**
     * 
     * @type {string}
     * @memberof Entry
     */
    'plant_id': string;
    /**
     * 
     * @type {string}
     * @memberof Entry
     */
    'notes': string | null;
    /**
     * 
     * @type {number}
     * @memberof Entry
     */
    'plant_health': number;
    /**
     * 
     * @type {string}
     * @memberof Entry
     */
    'timestamp': string;
}

