/* tslint:disable */
/* eslint-disable */
/**
 * Plant Tracker API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { Location } from './location';

/**
 * 
 * @export
 * @interface PlantCreateTrefle
 */
export interface PlantCreateTrefle {
    /**
     * 
     * @type {number}
     * @memberof PlantCreateTrefle
     */
    'id': number;
    /**
     * 
     * @type {string}
     * @memberof PlantCreateTrefle
     */
    'name': string;
    /**
     * 
     * @type {Location}
     * @memberof PlantCreateTrefle
     */
    'location': Location;
    /**
     * 
     * @type {number}
     * @memberof PlantCreateTrefle
     */
    'purchase_year'?: number;
    /**
     * 
     * @type {number}
     * @memberof PlantCreateTrefle
     */
    'purchase_month'?: number;
    /**
     * 
     * @type {number}
     * @memberof PlantCreateTrefle
     */
    'purchase_day'?: number;
}

