/* tslint:disable */
/* eslint-disable */
/**
 * Plant Tracker API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface PlantPatch
 */
export interface PlantPatch {
    /**
     * 
     * @type {string}
     * @memberof PlantPatch
     */
    'name': string;
    /**
     * 
     * @type {string}
     * @memberof PlantPatch
     */
    'photo_url'?: string;
    /**
     * 
     * @type {string}
     * @memberof PlantPatch
     */
    'location_id': string;
    /**
     * 
     * @type {string}
     * @memberof PlantPatch
     */
    'common_name': string;
    /**
     * 
     * @type {string}
     * @memberof PlantPatch
     */
    'scientific_name': string;
    /**
     * 
     * @type {string}
     * @memberof PlantPatch
     */
    'purchase_date'?: string;
    /**
     * 
     * @type {number}
     * @memberof PlantPatch
     */
    'trefle_id': number | null;
    /**
     * 
     * @type {string}
     * @memberof PlantPatch
     */
    'user_id': string;
}

