/* tslint:disable */
/* eslint-disable */
/**
 * Plant Tracker API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface PlantPatch
 */
export interface PlantPatch {
    /**
     * 
     * @type {string}
     * @memberof PlantPatch
     */
    'purchase_date'?: string | null;
    /**
     * 
     * @type {number}
     * @memberof PlantPatch
     */
    'trefle_id'?: number | null;
    /**
     * 
     * @type {string}
     * @memberof PlantPatch
     */
    'user_id'?: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof PlantPatch
     */
    'graveyard'?: boolean | null;
    /**
     * 
     * @type {string}
     * @memberof PlantPatch
     */
    'death_date'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PlantPatch
     */
    'name'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PlantPatch
     */
    'photo_url'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PlantPatch
     */
    'area_id'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PlantPatch
     */
    'common_name'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PlantPatch
     */
    'scientific_name'?: string | null;
}

