/* tslint:disable */
/* eslint-disable */
/**
 * Book Store API
 * Book Store API for renting books and notifying available/returned books in a store
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface PlantOut
 */
export interface PlantOut {
    /**
     * 
     * @type {string}
     * @memberof PlantOut
     */
    'id'?: string;
    /**
     * 
     * @type {string}
     * @memberof PlantOut
     */
    'name': string;
    /**
     * 
     * @type {string}
     * @memberof PlantOut
     */
    'common_name'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PlantOut
     */
    'scientific_name'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PlantOut
     */
    'purchase_date'?: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof PlantOut
     */
    'graveyard'?: boolean;
    /**
     * 
     * @type {string}
     * @memberof PlantOut
     */
    'death_date'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PlantOut
     */
    'main_photo'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PlantOut
     */
    'notes'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PlantOut
     */
    'area': string;
    /**
     * 
     * @type {string}
     * @memberof PlantOut
     */
    'user': string;
}

