# Generated by Django 5.0.3 on 2024-04-05 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_alter_plant_death_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='main_photo',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
