# Generated by Django 5.0.3 on 2024-04-05 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_plant_main_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant',
            name='common_name',
            field=models.TextField(blank=True, null=True),
        ),
    ]
