# Generated by Django 5.0.3 on 2024-04-11 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0007_entry_photo"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="activity",
            name="user",
        ),
    ]
