# Generated by Django 5.0.3 on 2024-04-19 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0010_alter_plant_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
