# Generated by Django 5.0.3 on 2024-04-24 11:57

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0011_plant_notes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='area',
            unique_together={('name', 'user')},
        ),
        migrations.AlterUniqueTogether(
            name='location',
            unique_together={('name', 'user')},
        ),
        migrations.AlterUniqueTogether(
            name='plant',
            unique_together={('name', 'user')},
        ),
    ]
