# Generated by Django 5.0.3 on 2024-04-24 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0014_remove_location_unique_by_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='area',
            name='name',
            field=models.TextField(),
        ),
    ]
