# Generated by Django 5.0.3 on 2024-05-01 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0017_alter_plant_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant',
            name='main_photo',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
