# Generated by Django 5.0.3 on 2024-07-30 21:24

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0018_alter_plant_main_photo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='search_vector',
            field=django.contrib.postgres.search.SearchVectorField(null=True),
        ),
        migrations.AddIndex(
            model_name='plant',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='tracker_pla_search__d4caa6_gin'),
        ),
    ]
