# Generated by Django 5.0.3 on 2024-07-30 21:24

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.conf import settings
from django.db import migrations

def compute_search_vector(apps, schema_editor):
    Entry = apps.get_model("tracker", "Entry")
    Entry.objects.update(search_vector=django.contrib.postgres.search.SearchVector("notes"))


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0021_entry_search_vector_and_more'),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
            CREATE TRIGGER search_vector_trigger
            BEFORE INSERT OR UPDATE OF notes
            ON tracker_entry
            FOR EACH ROW EXECUTE PROCEDURE
            tsvector_update_trigger(
                search_vector, 'pg_catalog.english', notes
            );
            UPDATE tracker_entry SET search_vector = NULL;
            """,
            reverse_sql="""
            DROP TRIGGER IF EXISTS search_vector_trigger
            ON tracker_entry;
            """,
        ),
        migrations.RunPython(
            compute_search_vector, reverse_code=migrations.RunPython.noop
        ),
    ]
