"""migration

Revision ID: f2f7e99f0349
Revises: 318b36d396f7
Create Date: 2023-09-28 22:34:10.577130

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f2f7e99f0349'
down_revision: Union[str, None] = '318b36d396f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('plant_source')
    op.drop_index('ix_source_id', table_name='source')
    op.drop_table('source')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('source',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('url', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='source_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index('ix_source_id', 'source', ['id'], unique=False)
    op.create_table('plant_source',
    sa.Column('plant_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('source_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['plant_id'], ['plant.id'], name='plant_source_plant_id_fkey'),
    sa.ForeignKeyConstraint(['source_id'], ['source.id'], name='plant_source_source_id_fkey'),
    sa.PrimaryKeyConstraint('plant_id', 'source_id', name='plant_source_pkey')
    )
    # ### end Alembic commands ###
