"""migration

Revision ID: 1fd7de581883
Revises: 06d2a466ad32
Create Date: 2024-02-03 23:27:12.566100

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1fd7de581883'
down_revision: Union[str, None] = '06d2a466ad32'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('plant', sa.Column('user_id', sa.UUID(), nullable=False))
    op.create_foreign_key(None, 'plant', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'plant', type_='foreignkey')
    op.drop_column('plant', 'user_id')
    # ### end Alembic commands ###
