"""migration

Revision ID: 1874c830ae9a
Revises: 14bedb9cfd97
Create Date: 2024-02-10 20:42:09.806178

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1874c830ae9a'
down_revision: Union[str, None] = '14bedb9cfd97'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('entry_plant',
    sa.Column('plant_id', sa.UUID(), nullable=False),
    sa.Column('entry_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['entry_id'], ['entry.id'], ),
    sa.ForeignKeyConstraint(['plant_id'], ['plant.id'], ),
    sa.PrimaryKeyConstraint('plant_id', 'entry_id')
    )
    op.drop_table('entry_source')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('entry_source',
    sa.Column('plant_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('entry_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['entry_id'], ['entry.id'], name='entry_source_entry_id_fkey'),
    sa.ForeignKeyConstraint(['plant_id'], ['plant.id'], name='entry_source_plant_id_fkey'),
    sa.PrimaryKeyConstraint('plant_id', 'entry_id', name='entry_source_pkey')
    )
    op.drop_table('entry_plant')
    # ### end Alembic commands ###
