"""migration

Revision ID: 081685adb7af
Revises: 959bf680d842
Create Date: 2024-02-02 03:21:16.640501

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '081685adb7af'
down_revision: Union[str, None] = '959bf680d842'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('plant_location')
    op.drop_table('plant_user')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plant_user',
    sa.Column('plant_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['plant_id'], ['plant.id'], name='plant_user_plant_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='plant_user_user_id_fkey'),
    sa.PrimaryKeyConstraint('plant_id', 'user_id', name='plant_user_pkey')
    )
    op.create_table('plant_location',
    sa.Column('plant_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('location_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['location_id'], ['location.id'], name='plant_location_location_id_fkey'),
    sa.ForeignKeyConstraint(['plant_id'], ['plant.id'], name='plant_location_plant_id_fkey'),
    sa.PrimaryKeyConstraint('plant_id', 'location_id', name='plant_location_pkey')
    )
    # ### end Alembic commands ###
