"""migration

Revision ID: 3cf008f8a089
Revises: 1874c830ae9a
Create Date: 2024-02-10 20:46:18.449953

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3cf008f8a089'
down_revision: Union[str, None] = '1874c830ae9a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('entry_plant')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('entry_plant',
    sa.Column('plant_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('entry_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['entry_id'], ['entry.id'], name='entry_plant_entry_id_fkey'),
    sa.ForeignKeyConstraint(['plant_id'], ['plant.id'], name='entry_plant_plant_id_fkey'),
    sa.PrimaryKeyConstraint('plant_id', 'entry_id', name='entry_plant_pkey')
    )
    # ### end Alembic commands ###
