"""migration

Revision ID: ff6ef91e49c6
Revises: 3cf008f8a089
Create Date: 2024-02-10 20:47:15.295652

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ff6ef91e49c6'
down_revision: Union[str, None] = '3cf008f8a089'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('entry_activity')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('entry_activity',
    sa.Column('activity_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('entry_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['activity_id'], ['activity.id'], name='entry_activity_activity_id_fkey'),
    sa.ForeignKeyConstraint(['entry_id'], ['entry.id'], name='entry_activity_entry_id_fkey'),
    sa.PrimaryKeyConstraint('activity_id', 'entry_id', name='entry_activity_pkey')
    )
    # ### end Alembic commands ###
