"""migration

Revision ID: 14bedb9cfd97
Revises: b27c4bb49191
Create Date: 2024-02-10 20:39:38.928974

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "14bedb9cfd97"
down_revision: Union[str, None] = "b27c4bb49191"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "entry_activity",
        sa.Column("activity_id", sa.UUID(), nullable=False),
        sa.Column("entry_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["activity_id"],
            ["activity.id"],
        ),
        sa.ForeignKeyConstraint(
            ["entry_id"],
            ["entry.id"],
        ),
        sa.PrimaryKeyConstraint("activity_id", "entry_id"),
    )
    op.drop_constraint("entry_activity_id_fkey", "entry", type_="foreignkey")
    op.drop_column("entry", "activity_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("entry", sa.Column("activity_id", sa.UUID(), autoincrement=False, nullable=False))
    op.create_foreign_key("entry_activity_id_fkey", "entry", "activity", ["activity_id"], ["id"])
    op.drop_table("entry_activity")
    # ### end Alembic commands ###
