"""migration

Revision ID: 0ce1f9aeed8a
Revises: 70b98b786805
Create Date: 2024-02-03 22:45:48.990305

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0ce1f9aeed8a'
down_revision: Union[str, None] = '70b98b786805'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_location_id', table_name='location')
    op.drop_table('location')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('location',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='location_pkey'),
    sa.UniqueConstraint('name', name='location_name_key')
    )
    op.create_index('ix_location_id', 'location', ['id'], unique=False)
    # ### end Alembic commands ###
