"""migration

Revision ID: 610440e3ed92
Revises: 49120a0590f3
Create Date: 2024-02-25 19:31:48.319034

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '610440e3ed92'
down_revision: Union[str, None] = '49120a0590f3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('location',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_location_id'), 'location', ['id'], unique=False)
    op.add_column('area', sa.Column('location_id', sa.UUID(), nullable=False))
    op.create_foreign_key(None, 'area', 'location', ['location_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'area', type_='foreignkey')
    op.drop_column('area', 'location_id')
    op.drop_index(op.f('ix_location_id'), table_name='location')
    op.drop_table('location')
    # ### end Alembic commands ###
