"""migration

Revision ID: a1b613e81314
Revises: 606b0ea99b30
Create Date: 2024-02-11 14:49:41.133975

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a1b613e81314'
down_revision: Union[str, None] = '606b0ea99b30'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('entry', sa.Column('timestamp', sa.DateTime(), nullable=False))
    op.drop_column('entry', 'date')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('entry', sa.Column('date', sa.DATE(), autoincrement=False, nullable=False))
    op.drop_column('entry', 'timestamp')
    # ### end Alembic commands ###
