"""migration

Revision ID: 0cdb14bb4fbb
Revises: f50434054241
Create Date: 2024-02-19 22:37:48.514212

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0cdb14bb4fbb'
down_revision: Union[str, None] = 'f50434054241'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('plant', sa.Column('graveyard', sa.Boolean(), nullable=True))
    op.add_column('plant', sa.Column('death_date', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('plant', 'death_date')
    op.drop_column('plant', 'graveyard')
    # ### end Alembic commands ###
