"""migration

Revision ID: 606b0ea99b30
Revises: 22730ab7c739
Create Date: 2024-02-11 14:39:55.801309

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '606b0ea99b30'
down_revision: Union[str, None] = '22730ab7c739'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('entry', sa.Column('plant_health', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('entry', 'plant_health')
    # ### end Alembic commands ###
