"""migration

Revision ID: 22730ab7c739
Revises: 09bbd56f6250
Create Date: 2024-02-11 14:31:00.982337

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '22730ab7c739'
down_revision: Union[str, None] = '09bbd56f6250'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('entry', sa.Column('notes', sa.String(), nullable=True))
    op.alter_column('entry', 'date',
               existing_type=sa.DATE(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('entry', 'date',
               existing_type=sa.DATE(),
               nullable=True)
    op.drop_column('entry', 'notes')
    # ### end Alembic commands ###
